version: "3.8"
services:
  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./reverse-proxy
    ports:
      - "80:80"
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  client:
    container_name: client
    build:
      context: ./frontend
    ports:
      - "3000:3000"